// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhalrlrwbfdfqcnmgcsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoYWxybHJ3YmZkZnFjbm1nY3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwOTQ2ODgsImV4cCI6MjA3NjY3MDY4OH0.AogOrgtAi9VCNe60bQA0LhHPibRK4SrYUqgu4PwPUck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});